### ISSUE TITLE
Enlace a Discord caducado

### ISSUE THREAD

**Issue by davidgasquez** [PyDataGRX/.github#1]
¡Hola! Parece que el [enlace a Discord](https://github.com/PyDataGRX/.github/blob/main/profile/README.md?plain=1#L19) ha caducado y no funciona.

El mismo enlace se está usando en [Linksta](https://linksta.cc/@PyDataGRX).

**Comment by DraXus** [comment]
Gracias @davidgasquez! He actualizado el enlace en el README. ¿Puedes probar de nuevo?

@thebooort puedes actualizarlo tú en el Linksta please?

**Comment by davidgasquez** [comment]
> ¿Puedes probar de nuevo?

¡Funciona! Gracias 😄

**Comment by thebooort** [comment]
> @thebooort puedes actualizarlo tú en el Linksta please?

Hecho! Cierro, pero feel free de reabrir si detectáis cualquier problema similar!
